name: bchfs-tests

on: [push, pull_request]

jobs:
  bchfs-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        python-version: ['3.7', '3.8']

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: |
          git submodule update --init
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Install
        run: |
          python setup.py -coverage develop

      - name: Tests
        run: | 
          coverage run --parallel-mode -m pytest tests/
          coverage combine
          coverage report -m
          coverage xml
          gcovr -r . -x -o .coverage_c.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: .coverage_c.xml,coverage.xml
